version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./jenkins:/var/jenkins_home/
    depends_on:
      - host
    links:
      - "host:agent"
  host:
    image: alpine
    container_name: host
    working_dir: /root/
    volumes:
      - ./configure.sh:/root/configure.sh
    user: root
    command: sh -c "/root/configure.sh"
    ports:
      - "8083:8083"
      - "32:32"

